### ISSUE TITLE
docker で実行できるように対応したい

### ISSUE THREAD

**Issue by yuukis** [opendata-yamanashi/yama-api#3]
現状、docker で yama-api を実行するために main.py を変更する必要がある。
docker でも直接実行できるよう対応したい。
(main.py を変更しなくても実行できる方法があれば知りたい)

----

### ①Dockerfile の作成
Dockerfile 
```
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim

COPY requirements.txt /tmp/requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt
```
### ②yama-api 用の docker イメージを作成 
```
$ docker build -t yama-api .
```
### ③yama-api を実行（ここでエラーとなってしまう）
```
$ docker run -p 8000:80 -v $(pwd)/app:/app -it yama-api

[2022-02-03 15:45:57 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/main.py", line 11, in <module>
    from app.constants import MAX_COUNT
ModuleNotFoundError: No module named 'app'
```

### ④docker で実行させるために変更した箇所
```
$ git diff
diff --git a/app/main.py b/app/main.py
index f3b1b2b..2a8bc87 100644
--- a/app/main.py
+++ b/app/main.py
@@ -8,15 +8,15 @@ import logging
 # from time import sleep
 from typing import List, Optional, Tuple
 from fastapi import FastAPI
-from app.constants import MAX_COUNT
-from app.yama_data import get_yama_dataframe
+from constants import MAX_COUNT
+from yama_data import get_yama_dataframe
 from fastapi.responses import ORJSONResponse
 from fastapi.middleware.cors import CORSMiddleware
 
 def _load_data(name: str) -> pd.DataFrame:
     """データのロード."""
-    with open('./app/resource.json', 'r') as f:
+    with open('./resource.json', 'r') as f:
         config = json.load(f)
     url = next(
             (c['url'] for c in config['sites'] if c['name'] == name),
```

**Comment by yuukis** [comment]
③で次のコマンドを実行することで動作しました！

```
$ docker run -p 8000:80 -v $(pwd)/app:/app/app -e PYTHONPATH="/" -e APP_MODULE="app.main:app" -it yama-api
```

解決しましたのでクローズします
